version: "3.8"
services:
    server_first:
        build:
            context: ./app
        environment:
          - NAME=First
        ports:
            - "8001:5000"
        container_name: server_first
        networks:
          - backbone
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"
        networks:
          - backbone
networks:
  backbone:
    driver: bridge